name: servidor
description: Servidor de simulacao e regras de automacao do BioSolar Citrus.
version: 1.0.0
publish_to: 'none'
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.12.2

# Add regular dependencies here.
dependencies:
  compartilhado:
    path: ../compartilhado
  shelf: ^1.4.2
  shelf_router: ^1.1.4
  shelf_web_socket: ^3.0.0
  web_socket_channel: ^3.0.3

dev_dependencies:
  lints: ^6.0.0
  test: ^1.25.6
